Domain\Entities\Veterinary:
    type: entity
    table: veterinary
    indexes:
        fk_veterinary_1_idx:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        crv:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        information:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
    manyToOne:
        user:
            targetEntity: Domain\Entities\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
