Domain\Entities\Country:
    type: entity
    table: country
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
        initials:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
    lifecycleCallbacks: {  }
