Domain\Entities\Manager:
    type: entity
    table: manager
    indexes:
        fk_manager_1_idx:
            columns:
                - company_id
        fk_manager_2_idx:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
    manyToOne:
        company:
            targetEntity: Domain\Entities\Company
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                company_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Domain\Entities\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
