Domain\Entities\User:
    type: entity
    table: user
    uniqueConstraints:
        email_UNIQUE:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        profile:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        thumbnail:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        confirmed:
            type: boolean
            nullable: false
            options:
                default: '0'
        resetPasswordToken:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: reset_password_token
        socialIdentifier:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: social_identifier
        socialProvider:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: social_provider
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
        socialId:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: social_id
        profileUrl:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: profile_url
        addressZipcode:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: address_zipcode
        addressStreet:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: address_street
        addressDistrict:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: address_district
        addressNumber:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: address_number
        addressCity:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: address_city
        addressState:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: address_state
        telephone:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        homeTelephone:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: home_telephone
        oneClickBuy:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: one_click_buy
        cardId:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: card_id
        cpf:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        birthday:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
