Domain\Entities\Customer:
    type: entity
    table: customer
    indexes:
        fk_customer_1_idx:
            columns:
                - company_id
        fk_customer_2_idx:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
        firstPetshop:
            type: boolean
            nullable: true
            options:
                default: '0'
            column: first_petshop
    manyToOne:
        company:
            targetEntity: Domain\Entities\Company
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                company_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: Domain\Entities\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
