Domain\Entities\City:
    type: entity
    table: city
    indexes:
        fknew_Cidade_estado:
            columns:
                - state_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 120
            options:
                fixed: false
    manyToOne:
        state:
            targetEntity: Domain\Entities\State
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                state_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
