Domain\Entities\Cache:
    type: entity
    table: cache
    uniqueConstraints:
        cache_key_unique:
            columns:
                - key
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        key:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        value:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        expiration:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
