<?php
/**
 * Created by PhpStorm.
 * User: davi
 * Date: 7/17/17
 * Time: 11:36 PM
 */

namespace Domain\Entities;

class CNAE{

    public function getCNAE()
    {
        return [
            '2122000'=>'VACINAS PARA PEQUENOS ANIMAIS; FABRICAÇÃO DE',
            '2833000'=>'COMEDOUROS E BEBEDOUROS PARA ANIMAIS; FABRICAÇÃO DE',
            '3240099'=>'BRINQUEDOS, DE QUALQUER MATERIAL, PARA ANIMAIS; FABRICAÇÃO DE',
            '3822000'=>'ANIMAIS INTOXICADOS (VIVOS OU MORTOS); TRATAMENTO E DISPOSIÇÃO DE',
            '4623199'=>'MELAÇO (COMPLEMENTO ALIMENTAR PARA ANIMAIS); COMÉRCIO ATACADISTA DE',
            '4618499'=>'SAL MINERAL E OUTROS ALIMENTOS PARA ANIMAIS; REPRESENTANTE COMERCIAL DE',
            '162899'=>'ESTABULAÇÃO, CUIDADO E REPRODUÇÃO DE ANIMAIS DE TERCEIROS',
            '4646001'=>'PRODUTOS DE HIGIENE E PERFUMARIA PARA USO VETERINÁRIO; COMÉRCIO ATACADISTA DE',
            '7500100'=>'CONSULTÓRIO VETERINÁRIO',
            '2063100'=>'PRODUTOS DE HIGIENE E PERFUMARIA PARA ANIMAIS; FABRICAÇÃO DE',
            '8230001'=>'EXPOSIÇÃO DE ANIMAIS EM FEIRAS',
            '6550200'=>'PLANOS DE SAÚDE PARA ANIMAIS',
            '6622300'=>'CORRETOR DE PLANOS DE SAÚDE PARA ANIMAIS',
            '4789004'=>'Comércio varejista de animais vivos e de artigos e alimentos para animais de estimação ',
            '4781400'=>'VESTUÁRIO, ROUPAS PARA ANIMAIS; COMÉRCIO VAREJISTA DE',
            '4772500'=>'PRODUTOS DE HIGIENE E PERFUMARIA PARA USO VETERINÁRIO; COMÉRCIO VAREJISTA',
            '9499500'=>'ASSOCIAÇÃO DE PROTEÇÃO DE ANIMAIS',
            '1510600'=>'COUROS E PELES DE ANIMAIS DOMÉSTICOS; CURTIMENTO E OUTRAS PREPARAÇÕES DE',
            '1529700'=>'FOCINHEIRAS, MORDAÇAS, COLEIRAS E OUTROS ARTIGOS DE COURO PARA PEQUENOS ANIMAIS; FABRICAÇÃO DE',
            '4611700'=>'ANIMAIS VIVOS; REPRESENTANTE COMERCIAL E AGENTE DO COMÉRCIO DE',
            '4664800'=>'MÁQUINAS, APARELHOS E EQUIPAMENTOS PARA USO VETERINÁRIO; COMÉRCIO ATACADISTA DE',
            '4623101'=>'ANIMAIS VIVOS; COMÉRCIO ATACADISTA DE',
            '4930201'=>'TRANSPORTE RODOVIÁRIO DE ANIMAIS VIVOS, MUNICIPAL',
            '4642701'=>'VESTUÁRIO, ROUPAS PARA ANIMAIS; COMÉRCIO ATACADISTA DE',
            '8011102'=>'ADESTRAMENTO DE CÃES DE GUARDA; SERVIÇO DE',
            '4930202'=>'TRANSPORTE RODOVIÁRIO DE ANIMAIS VIVOS, INTERMUNICIPAL, INTERESTADUAL E INTERNACIONAL',
            '4644302'=>'DISTRIBUIDORA DE MEDICAMENTOS DE USO VETERINÁRIO; COMÉRCIO ATACADISTA DE',
            '9603302'=>'CAPTURA E CREMAÇÃO DE ANIMAIS DOMÉSTICOS ABANDONADOS EM VIAS PÚBLICAS - CARROCINHA',
            '159802'=>'ANIMAIS DOMÉSTICOS CRIACAO DE',
            '4771704'=>'PRODUTOS FARMACÊUTICOS MANIPULADOS PARA USO VETERINÁRIO, COMÉRCIO VAREJISTA',
            '9609207'=>'ALOJAMENTO DE ANIMAIS DOMÉSTICOS; SERVIÇOS DE',
            '9609208'=>'HIGIENE E EMBELEZAMENTO DE ANIMAIS DOMÉSTICOS',
            '4623109'=>'RAÇÃO E OUTROS PRODUTOS ALIMENTÍCIOS PARA ANIMAIS; COMÉRCIO ATACADISTA DE',
            '3314711'=>'APARELHOS E MÁQUINAS PARA APICULTURA E CRIAÇÃO DE PEQUENOS ANIMAIS, MANUTENÇÃO',
        ];
    }


    public function getValid()
    {
        return array_keys($this->getCNAE());
    }
}
